version: '3.8'

services:
  app:
    container_name: mysite_app
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # Persiste o banco de dados SQLite na pasta prisma do host
      - ./prisma/dev.db:/app/dev.db
    environment:
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=production
